#!/usr/bin/env bash
set -Eeuo pipefail

_version="${1:-\2}"
_hash="${2:-$(git rev-parse --short=9 HEAD)}"

function print_url_and_hash() {
  set -Eeuo pipefail
  _postfix="${1}"
  _url="https://github.com/chipsalliance/verible/releases/download/v${_version}-${_hash}/verible-v${_version}-${_hash}-${_postfix}"
  echo    "    url = ${_url}"
  echo -n "    sha256 = "
  curl -fsSLo- "${_url}" | sha256sum - | cut -d' ' -f1
}

linux_entry=$(print_url_and_hash linux-static-x86_64.tar.gz)
win_entry=$(print_url_and_hash win64.zip)
mac_entry=$(print_url_and_hash macOS.tar.gz)

cat >setup.cfg <<-EOF
[metadata]
name = verible_py
version = v${_version}
description = Python wrapper around invoking verible (https://chipsalliance.github.io/verible/)
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/chipsalliance/verible
author = Henner Zeller
author_email = h.zeller@acm.org
license = Apache-2.0
license_files = LICENSE
classifiers =
    License :: OSI Approved :: Apache Software License
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3 :: Only
    Programming Language :: Python :: Implementation :: CPython
    Programming Language :: Python :: Implementation :: PyPy

[options]
python_requires = >=3.8
setup_requires =
    setuptools-download

[setuptools_download]
download_scripts =
    [verible-verilog-lint]
    group = verible-verilog-lint
    marker = sys_platform == "linux" and platform_machine == "x86_64"
${linux_entry}
    extract = tar
    extract_path = verible-v${_version}-${_hash}/bin/verible-verilog-lint
    [verible-verilog-format]
    group = verible-verilog-format
    marker = sys_platform == "linux" and platform_machine == "x86_64"
${linux_entry}
    extract = tar
    extract_path = verible-v${_version}-${_hash}/bin/verible-verilog-format
    [verible-verilog-lint]
    group = verible-verilog-lint
    marker = sys_platform == "darwin" and platform_machine == "x86_64"
    marker = sys_platform == "darwin" and platform_machine == "arm64"
${mac_entry}
    extract = tar
    extract_path = verible-v${_version}-${_hash}-macOS/bin/verible-verilog-lint
    [verible-verilog-format]
    group = verible-verilog-format
    marker = sys_platform == "darwin" and platform_machine == "x86_64"
    marker = sys_platform == "darwin" and platform_machine == "arm64"
${mac_entry}
    extract = tar
    extract_path = verible-v${_version}-${_hash}-macOS/bin/verible-verilog-format
    [verible-verilog-lint.exe]
    group = verible-verilog-lint
    marker = sys_platform == "win32" and platform_machine == "AMD64"
    marker = sys_platform == "cygwin" and platform_machine == "x86_64"
${win_entry}
    extract = zip
    extract_path = verible-v${_version}-${_hash}-win64/verible-verilog-lint.exe
    [verible-verilog-format.exe]
    group = verible-verilog-format
    marker = sys_platform == "win32" and platform_machine == "AMD64"
    marker = sys_platform == "cygwin" and platform_machine == "x86_64"
${win_entry}
    extract = zip
    extract_path = verible-v${_version}-${_hash}-win64/verible-verilog-format.exe
EOF
